# -*- coding: utf-8 -*-
"""model_testing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dUanJgMr5XFj7VimQ7OlxLzStuLlx6PD
"""

import pandas as pd
import pickle
from sklearn.metrics import accuracy_score

with open('logistic.pkl', 'rb') as f:
    model = pickle.load(f)

test_data = pd.read_csv('test/test_Data_distances.csv')


x_test = test_data[['firstrazr', 'secondrazr', 'thirdrazr']]
y_test = test_data['Class']


scaler = pickle.load(open('d_preprocessing.pkl', 'rb'))['scaler']
x_test_scaled = scaler.transform(x_test)


y_pr = model.predict(x_test_scaled)

test_accuracy = accuracy_score(y_test, y_pr)

print(f"аccuracy: {test_accuracy}")