# -*- coding: utf-8 -*-
"""model_preprocessing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1i5bElkGMdO8EybmXsQzscFLezIpmUD-r
"""

import pandas as pd
import pickle
from sklearn.preprocessing import  StandardScaler
from sklearn.model_selection import train_test_split


d = pd.read_csv('train/train_Data_distances.csv')


print(d.describe())

count_class = d.groupby('Class').size()
print(count_class)
#корреляционная матрица
correl = d.corr(numeric_only = True)
print(correl)

# целевая переменная y
X = d[['firstrazr', 'secondrazr', 'thirdrazr']]
y = d['Class']


# стандартизация данных
stnd = StandardScaler()
X_stnd = stnd.fit_transform(X)

# разбиение на тренировочные и обучающиеся
X_train, X_val, y_train, y_val = train_test_split(X_stnd, y, test_size=0.2, random_state=42)

#объединение
d_preprocessing = {
    'X_train': X_train,
    'X_val': X_val,
    'y_train': y_train,
    'y_val': y_val,
    'scaler': stnd
}


file1 = 'd_preprocessing.pkl'# сохранение
with open(file1, 'wb') as f:
    pickle.dump(d_preprocessing, f)
pd.to_pickle(d_preprocessing, file1)

print(f"Данные предобработанны и успешно сохранены в файл {file1}")