# -*- coding: utf-8 -*-
"""model_preparation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11i5pUp8xmqfu7mQoNo4nYeQA7qkUl6U1
"""

import pandas as pd
import pickle
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report

d_preprocessing = pd.read_pickle('d_preprocessing.pkl')

X_train = d_preprocessing['X_train']
y_train = d_preprocessing['y_train']


d_log = LogisticRegression()# обучение логистической регрессии
d_log.fit(X_train, y_train)


file2 = 'logistic.pkl' # сохранение тренировочной модели
with open(file2, 'wb') as f:
    pickle.dump(d_log, f)

print(f"обучение-выполнено, модель сохранена в {file2}")


y_pr = d_log.predict(X_train)
accuracy = accuracy_score(y_train, y_pr)
print(accuracy)
print(classification_report(y_train, y_pr))